---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-controller
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-controller
  template:
    metadata:
      labels:
        app: tenant-controller
    spec:
      containers:
      - name: controller
        image: tenant-controller:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tenant-controller
  namespace: metacontroller
spec:
  selector:
    app: tenant-controller
  ports:
  - port: 8080