---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: tenant-controller
spec:
  resyncPeriodSeconds: 10
  generateSelector: true
  parentResource:
    apiVersion: projectx.mavenwave.dev/v1
    resource: tenants
  childResources:
  - apiVersion: v1
    resource: namespaces
    updateStrategy:
      method: InPlace
  - apiVersion: rbac.authorization.k8s.io/v1
    resource: roles
    updateStrategy:
      method: InPlace
  - apiVersion: rbac.authorization.k8s.io/v1
    resource: rolebindings
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://tenant-controller.tenant-system:8080/sync