---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-projectx-mavenwave-dev-v1alpha1-tenant
  failurePolicy: Fail
  name: mtenant.kb.io
  rules:
  - apiGroups:
    - projectx.mavenwave.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tenants
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-projectx-mavenwave-dev-v1alpha1-tenant
  failurePolicy: Fail
  name: vtenant.kb.io
  rules:
  - apiGroups:
    - projectx.mavenwave.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tenants
  sideEffects: None
