# permissions for end users to edit tenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tenant-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: projectx-tenants
    app.kubernetes.io/part-of: projectx-tenants
    app.kubernetes.io/managed-by: kustomize
  name: tenant-editor-role
rules:
- apiGroups:
  - projectx.mavenwave.dev
  resources:
  - tenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - projectx.mavenwave.dev
  resources:
  - tenants/status
  verbs:
  - get
