# permissions for end users to view tenantclouds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tenantcloud-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: projectx-tenants
    app.kubernetes.io/part-of: projectx-tenants
    app.kubernetes.io/managed-by: kustomize
  name: tenantcloud-viewer-role
rules:
- apiGroups:
  - projectx.mavenwave.dev
  resources:
  - tenantclouds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - projectx.mavenwave.dev
  resources:
  - tenantclouds/status
  verbs:
  - get
