apiVersion: projectx.mavenwave.dev/v1alpha1
kind: Tenant
metadata:
  labels:
    app.kubernetes.io/name: tenant
    app.kubernetes.io/instance: tenant-sample
    app.kubernetes.io/part-of: projectx-tenants
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: projectx-tenants
  annotations:
    foo: bar
  name: tenant-sample
spec:
  admins:
  - apiGroup: ""
    kind: User
    name: foo@example.com
  - apiGroup: ""
    kind: "User"
    name: biz@example.com
  - apiGroup: ""
    kind: ServiceAccount
    name: default
  viewers:
  - apiGroup: ""
    kind: User
    name: bar@example.com
  - apiGroup: ""
    kind: User
    name: baz@example.com
  - apiGroup: ""
    kind: ServiceAccount
    name: default
    namespace: default
  infrastructure:
    gcp:
      enabled: false
      serviceAccount: nextgen-devops@bradw-nextgen-devops.iam.gserviceaccount.com
      generateAccessToken: false
